export const REQUEST_ONGOING_INCIDENTS = 'REQUEST_ONGOING_INCIDENTS';
export const RECEIVE_ONGOING_INCIDENTS = 'RECEIVE_ONGOING_INCIDENTS';
export const REQUEST_ONGOING_INCIDENTS_FAIL = 'REQUEST_ONGOING_INCIDENTS_FAIL';

export const REQUEST_MINE_INCIDENTS = 'REQUEST_MINE_INCIDENTS';
export const RECEIVE_MINE_INCIDENTS = 'RECEIVE_MINE_INCIDENTS';
export const REQUEST_MINE_INCIDENTS_FAIL = 'REQUEST_MINE_INCIDENTS_FAIL';

export const ACCEPT_INCIDENT_REQUEST = 'ACCEPT_INCIDENT_REQUEST';
export const ACCEPT_INCIDENT_SUCCESS = 'ACCEPT_INCIDENT_SUCCESS';
export const ACCEPT_INCIDENT_FAILURE = 'ACCEPT_INCIDENT_FAILURE';

export const RESOLVE_INCIDENT_REQUEST = 'RESOLVE_INCIDENT_REQUEST';
export const RESOLVE_INCIDENT_SUCCESS = 'RESOLVE_INCIDENT_SUCCESS';
export const RESOLVE_INCIDENT_FAILURE = 'RESOLVE_INCIDENT_FAILURE';


export const REQUEST_HELP_INSTRUCTIONS = 'REQUEST_HELP_INSTRUCTIONS';
export const RECEIVE_HELP_INSTRUCTIONS = 'RECEIVE_HELP_INSTRUCTIONS';
export const REQUEST_HELP_INSTRUCTIONS_FAIL = 'REQUEST_HELP_INSTRUCTIONS_FAIL';

export const VOLUNTEERS_CHANGED_FOR_INCIDENT = 'VOLUNTEERS_CHANGED_FOR_INCIDENT';
export const VOLUNTEER_LOCATION_CHANGED = 'VOLUNTEER_LOCATION_CHANGED';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';

export const ENTER_SUCCESS = 'ENTER_SUCCESS';
export const ENTER_FAILURE = 'ENTER_FAILURE';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
